Simple sorting of photos by date inside album.
cozy/cozy-photos-v2 pull request #232
Opened 2016-10-17 09:51 UTC by MonsieurLanza

This follows my previous PR.
Left to do : sorting the view while editing the album. You have to go back on album list and then back again to the alum to view photos sorted by date.

2016-10-18 14:28 UTC, MonsieurLanza commented
Added date & GPS for photos added from files.
Patches photos with no dates. Old photos with from files already patched with GPS data will not have date updated, though.

2016-10-19 08:48 UTC, aenario requested changes

2016-10-19 08:48 UTC, aenario commented on server/controllers/file.coffee
>          if photo.binary?.thumb? and photo.binary.screen?
All the code below this line should be indented once more in order to be part of extractGpsFromBinary callback. Otherwise, the changes you make (date, gps) wont be applied to the photo JSON returned by creation.

2016-10-19 08:50 UTC, aenario commented
Thanks @MonsieurLanza ! 

There is a little change to be made regarding callbacks.

2016-10-19 11:23 UTC, MonsieurLanza commented on server/controllers/file.coffee
>          if photo.binary?.thumb? and photo.binary.screen?
I'd love to, and in fact it was my first attempt.

But extractGpsFromBinary do not pass the new object to the callback.
From the model :

```
    extractGpsFromBinary: (callback) ->
        kind = if @binary.raw then 'raw' else 'file'
        res  = @getBinary kind, (err) ->
            log.error err if err?

        res.on 'ready', (stream) =>
            Helpers.readMetadata stream, (err, data) =>
                if err?
                    log.error "Error reading metadata of #{@id} / #{@title}"
                    log.error err
                    callback()
                else
                    @updateAttributes { gps: data.exif.gps }, (err) ->
                        log.error err if err?
                        callback() # ~ next()
```

2016-10-19 13:29 UTC, MonsieurLanza commented on server/controllers/file.coffee
>          if photo.binary?.thumb? and photo.binary.screen?
And changing the callback args would break Photo.PatchGps().

2016-10-21 09:34 UTC, aenario commented on server/controllers/file.coffee
>          if photo.binary?.thumb? and photo.binary.screen?
Yes, but @updateAttributes will set the changes (date & gps) on the instance object (`this` in extractGpsFromBinary, `photo` in controllers/file).
 
So, when callback is called (no matter its arguments), photo.gps and photo.date should be set in controllers/file

2017-07-28 09:25 UTC, closed without merging